# Generated by Django 4.0.3 on 2022-04-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="dates",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
