# Generated by Django 3.2.9 on 2022-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_habit_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
